### PR TITLE
Example NXcontainer files - XPDF

### PR DESCRIPTION
**Pull request by mtwharmby**
Signed-off-by: Michael Wharmby <michael.wharmby@diamond.ac.uk>

### CODE REVIEW

**Comment by zjttoefs** [comment]
I guess they are SWMR files and require HDF5 1.10
No problem opening them with h5dump 1.10.1 

Updating the Readme is not a bad idea, though. For now we just wanted to have access to the files and the pull request was a way to have them publicly available.

**Comment by mtwharmby** [comment]
Indeed they are SWMR. I'll rebuild them SWMR free and update the readme.

**Comment by zjttoefs** [comment]
Looks like you are nesting NXsample groups. It should be NXsample_component groups going into NXsample.

I would have expected the NXcontainer to be part of NXsample. 

The information contained doesn't appear that meaningful to me. One contains an empty orientation group. And a zero distance from the sample, recorded by NXbeam. Which is both expected and odd.
I'm not sure to do with the packing fraction of the container (we call that volume_fraction elsewhere, right?). Reference_data points to a file (not an entry in one), but what does this reference mean? To I need to parse the name and description to find out what to do with the data?

**Comment by zjttoefs** [comment]
@mtwharmby Don't make them SWMR free! If that's what you're generating, we know what we need to be able to read. This is good.

**Comment by prjemian** [comment]
I suggest that once we are confident the structure is right, that you
deposit two sets, one with SWMR and the other without.  We need examples
with SWMR but the examples are not useful until those libraries propagate
into the community.  The README will identify each.

**Comment by mtwharmby** [comment]
The files have been generated by hand and not by the acquisition software hence most of the real values are missing. I was under the impression you wanted to see the structure that I was aiming for rather than a feature complete file (a feature complete file brings us to a chicken and egg problem, because what spec should I write the file to...? I am more than happy to just go ahead and say this is the way we're going to write these files, but then if I'm told it should be different then we break backward compatibility, not to mention our analysis software).

NXsample is nested inside NXsample because the current framework I'm using to write the files (DAWN libraries: org.eclipse.dawnsci.nexus) doesn't have support for NXsamplecomponent. I have requested it, but there's nothing else I can do for the minute.

NXcontainer can sit inside NXsample. My thought was NXcontainer contains information that does not pertain to the sample itself (though I appreciate this is arguable). I'm open to making that change. Just to reiterate what I said in yesterday's telco, the whole point of the container is to encode a hierarchy of measurements:
sample is inside container is inside bigger container is inside beamline

During total scatttering data collections we measure each of these datasets:
1) sample is inside container is inside bigger container is inside beamline
2) container is inside bigger container is inside beamline
3) bigger container is inside beamline
4) beamline

During PDF processing we need to know which beamline and container(s) we used and how they relate to one-another in space (i.e. what's inside/before/after what) to build up our beam path. We might have several measurements of different containers in different combinations, so to maintain data provenance its important to record the correct hierarchy. This allows us to subtract scattering data that doesn't come from the sample, which is standard practice in PDF processing.

This is so we can subtract the container scattering data from the sample scattering data (this is how one produces a total scattering dataset). To do that subtraction successfully and to make other necessary corrections, we need to have a model for the beam path. NXbeam is included to express where the centre of mass of the container is relative to the sample (my example is a capillary, thus the centre of mass is coincident with the sample's, i.e. distance=0). NXtransformations (orientation) is used to apply rotations/translations so the sample and container data have the same orientation in space. packing_fraction expresses how well the stuff inside the container is packed. There is some similarity to volume fraction, though that is a property of the sample itself. What I am trying to express here is how well the sample fills the capillary (you could imagine an intrinsically porous material which has an intrinsic volume fraction, but the individual particles of which pack in the container with a particular packing efficiency - i.e. packing fraction). The reference_data is supposed to provide a way to link down to the actual measured container data (this is our data provenance). I would be happy to include a link to the entry, but by doing that as part of the spec, won't the files become fragile (I move my container measurement to a different directory and now the link is dead)? I provided a string file path as at least then software/users can inspect the value of the field and understand why their file no-longer works. Would it be an idea to include both perhaps?

The example I have provided was intentionally simple and to be easier to follow. I can build a more complex example based on the furnace I show in the docs, but this may be more confusing. Also as we are waiting for the spec to develop before completing the analysis tools in DAWN, it may be difficult to show *exactly* how this will be used in anger.

**Comment by mtwharmby** [comment]
Don't have time to fix this for the telco. Will close for now and put in a fresh request in the next few weeks.

**Pull request closed without merging**
