### PR TITLE
Script gen issue 24

### PR DESCRIPTION
**Pull request by RussBerg**
This PR adds python scripts for each application definition using h5py as well as nexusformat
addresses issue #24

### CODE REVIEW

**Comment by rayosborn** [comment]
Here are a few changes I would suggest for the nexusformat versions of the code.

* The code should not set the attribute `NX_class`, since that is already done when the group is initialized. For example, in the following, `NX_class` is automatically set to 'NXentry'.
```
root['/entry'] = NXentry()
```
* The code should not set the NXroot attributes at the end, since they are all set automatically when you call `root.save`.
```
root.attrs['file_name'] = os.path.abspath('NXarchive')
root.attrs['file_time'] = datetime.datetime.now().isoformat()
root.attrs['nexusformat_version'] = nexusformat.__version__
root.attrs['HDF5_Version'] = h5py.version.hdf5_version
root.save('nexusformat_NXarchive.h5', 'w')
```
One consequence of removing these lines is that you can remove all import statements at the top, except for `from nexusformat.nexus import *`. 
* There could be counter-arguments, but the nexusformat package recognizes both '.h5' and '.nxs' as valid file extensions. That might be an alternate method of differentiating the two sets of code (h5py and nexusformat) than using the file prefix.

Thanks for doing all this work.

**Comment by rayosborn** [comment]
This is looking good. I confirmed that I could use run NXarchive.py as a script and read in the saved data into NeXpy, without any issues. All the 'EX_doc' attributes have a blank space at the beginning of the string. Is that intended? If so, this looks good-to-go from the nexusformat API side.

**Comment by RussBerg** [comment]
> This is looking good. I confirmed that I could use run NXarchive.py as a script and read in the saved data into NeXpy, without any issues. All the 'EX_doc' attributes have a blank space at the beginning of the string. Is that intended? If so, this looks good-to-go from the nexusformat API side.

nope I can fix that, it was a result of an attempt to strip the doc strings that were ending up with tons of space characters so I had whittled everything down to a single space but didn't check to see if it was the first character in the entire string.

**Review by rayosborn — APPROVED** [review]
I was able to load a nexusformat-generated file without issue, so I think this looks good. The only thing I noticed is that you add a `signal=1` attribute to the data NXfield in an NXdata group. I think this is now officially deprecated. However, you also add a `signal` attribute to the group itself, so I think the file is still compliant.

**Pull request merged**
