### PR TITLE
Add documentation to the autogenerated examples

### PR DESCRIPTION
**Pull request by woutdenolf**
Add the README files to be linked in the nexusformat manual under code examples.

https://github.com/woutdenolf/exampledata/blob/add_examples_documentation/autogenerated_examples/nxdl/python_scripts/nexusformat/README.md

https://github.com/woutdenolf/exampledata/blob/add_examples_documentation/autogenerated_examples/nxdl/python_scripts/nexusformat/README.md

These README files are auto-generated just like the scripts and the hdf5 files.

### CODE REVIEW

**Review by RussBerg — CHANGES_REQUESTED** [review]
although the files in the **applications**  directory pointed to by the "result" links are not the actual output of these example scripts when executed, the files they produce are identical, that said I think it could lead to confusion down the road as the word **result** indicates the file is each scripts output, and it's not really true and certainly not true for the **nexusformat** scripts.  

I think it makes more sense to have a README.md for the **applications** directory as well
that has the links to the **.hdf5** files and then on each of these python script README's just add a sentence at the top that says these are autogenerated examples showing what it takes to create each file that will pass cnxvalidate, and remove the "result" link.

**Comment by woutdenolf** [comment]
@RussBerg What if I replace `result` with `example`?

**Comment by woutdenolf** [comment]
@RussBerg  I modified the README files a bit. From the documentation POV it is better imo to provide the links to the scripts and the examples together.

**Review by RussBerg — CHANGES_REQUESTED** [review]
hey @woutdenolf , just changing it to the word **example** to me doesn't avoid the possible confusion down the road I was talking about, these generated scripts don't create the hdf5 files that are found in the **applications** directory, both the hdf files in the **applications** directory and the scripts that appear in the **h5py** and **nexusformat** directories are only **output** of the execution of the **nxdl_to_hdf5.py** script, so to me there needs to be that distinction. So to present both beside each other suggests the hdf file is the product (in content and resulting location) of executing the script, which it isn't and that's why I would not like them presented together side by side. 

I think if you want to include the links to the hdf5 files in each README then there needs to be  sentence at the top that makes it clear saying "here are scripts you can execute that will produce hdf5 files that will pass cnxvalidate" and "also here are example hdf5 files that were generated using nxdl_to_hdf5.py"

**Review by prjemian — APPROVED** [review]
This is what I had in mind.  Thanks!

**Comment by RussBerg** [comment]
sure, not a hill I am willing to die on :), if confusion comes down the line it can be dealt with then

**Review by RussBerg — APPROVED** [review]

**Pull request merged**
